spring.application.name=simplerest
server.port=8082

# Database
spring.datasource.url=jdbc:mysql://localhost:3306/employees?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Pa$$w0rd
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Thymeleaf
spring.thymeleaf.cache=false

# Actuator
management.server.port=9090
management.endpoints.web.exposure.include=health,info,metrics,prometheus,env,loggers,threaddump

# Swagger (si activé via springdoc)
springdoc.show-actuator=true
springdoc.use-management-port=true

# Logging
logging.file.name=logs/app.log
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=DEBUG

# JWT (Base64)
security.jwt.secret=bmVzdHZvaWNlZGVjaWRlYW55dGhpbmdzaG9lb3JkZXJ3b3JsZHdoZXJldmVyc2VsZWM=
security.jwt.expiration-ms=86400000

app.admin.firstname=Patrick
app.admin.lastname=Dimbisoa
app.admin.password=Ma$terkey1


